//
//  sna_phrase_tbl.js
//
//  Copyright 2014 Roland Corporation. All rights reserved.
//

globals.parameter.phrase.snaPhraseTbl = [
	"No Assign",
	"Ac.Piano 1",
	"Ac.Piano 2",
	"E.Piano 1",
	"E.Piano 2",
	"Clav",
	"Glockenspiel",
	"Vibraphone",
	"Marimba",
	"Xylophone",
	"TubularBells",
	"Santoor",
	"Organ 1",
	"Organ 2",
	"Accordion",
	"Bandoneon",
	"Harmonica",
	"Nylon Guitar",
	"Flamenco Gt",
	"Ukulele",
	"SteelStr Gt1",
	"SteelStr Gt2",
	"SteelStr Gt3",
	"Mandolin",
	"Jazz Guitar",
	"E.Guitar 1",
	"E.Guitar 2",
	"E.Guitar 3",
	"E.Guitar 4",
	"Ac.Bass",
	"Fingered Bs",
	"Picked Bass",
	"Fretless Bs",
	"Violin",
	"Viola",
	"Cello",
	"Contrabass",
	"Solo Pizz",
	"Harp",
	"Yang Chin",
	"Timpani ",
	"Strings",
	"Strings Pizz",
	"Choir",
	"Trumpet 1",
	"Trumpet 2",
	"Trumpet 3",
	"Trumpet 4",
	"Trombone",
	"Tuba",
	"Mute Trumpet",
	"French Horn",
	"Soprano Sax",
	"Alto Sax",
	"Tenor Sax",
	"Baritone Sax",
	"Oboe",
	"English Horn",
	"Bassoon",
	"Clarinet 1",
	"Clarinet 2",
	"Piccolo",
	"Flute",
	"Recorder",
	"Pan Flute",
	"Tin Whistle",
	"Shakuhachi",
	"Ryuteki",
	"Ocarina",
	"Sitar",
	"Tsugaru",
	"Sansin",
	"Koto",
	"Taisho Koto",
	"Kalimba",
	"Pipes 1",
	"Pipes 2",
	"Erhu",
	"Sarangi",
	"Steel Drums",
	"One Shot",
	"Gliss",
	"Wah Clav",
	"Rasgueardo",
	"Oct Jazz Gt",
	"Wah Cut Gt",
	"Wah OD Gt",
	"Wah DS Gt"
];



